"""Installer worker; executed with Python inside the selected Resolve container."""

import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import venv


SIGNATURE = '"""Generated by Resolve Timer Linux installer."""'


def launcher_text(project):
    return f'''{SIGNATURE}
import runpy

runpy.run_path(
    {str(project / "scripts" / "ResolveTimer.py")!r},
    init_globals={{
        "resolve": globals().get("resolve"),
        "fusion": globals().get("fusion"),
        "bmd": globals().get("bmd"),
    }},
    run_name="__main__",
)
'''


def check_destination(launcher):
    for path in (launcher, *launcher.parents):
        if path.is_symlink():
            raise RuntimeError(f"Refusing a symlink in launcher destination: {path}")
    if launcher.exists() and not launcher.read_text().startswith(SIGNATURE):
        raise RuntimeError(f"Existing launcher is not managed by this installer: {launcher}")


def install_launcher(project, launcher):
    check_destination(launcher)
    database = project / "timer_db.yaml"
    # Exclusive creation preserves existing user data, including on repeat installs.
    if not database.exists():
        with database.open("x", encoding="utf-8") as handle:
            handle.write((project / "examples" / "timer_db.yaml").read_text())
    launcher.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=launcher.parent,
                                     delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(launcher_text(project))
    try:
        temporary.replace(launcher)
    finally:
        temporary.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    project = Path(__file__).resolve().parents[1]
    launcher = (Path.home() / ".local/share/DaVinciResolve/Fusion/Scripts/Utility"
                / "Resolve Timer/ResolveTimer.py")
    if sys.version_info < (3, 10):
        raise RuntimeError("Resolve Timer requires Python 3.10 or newer")
    if not Path("/opt/resolve/bin/resolve").is_file():
        raise RuntimeError("Resolve was not found at /opt/resolve/bin/resolve in this container")
    for relative in ("scripts/ResolveTimer.py", "src/resolve_timer/ui.py",
                     "requirements-resolve.txt", "examples/timer_db.yaml"):
        if not (project / relative).is_file():
            raise RuntimeError(f"Checkout is incomplete or not visible: {project / relative}")
    check_destination(launcher)
    target = project / ".resolve_deps"
    if target.is_symlink() or (target.exists() and not target.is_dir()):
        raise RuntimeError(f"Unexpected dependency destination: {target}")
    print(f"Python: {sys.executable} ({sys.version.split()[0]})", flush=True)
    print(f"Checkout: {project}\nDependencies: {target}\nLauncher: {launcher}", flush=True)
    if args.dry_run:
        print("Dry run: no files changed. Installation will use a temporary pip environment.")
        return

    # Stage and verify before replacing the current dependencies. Using the container's
    # interpreter ensures native Pillow extensions match its Python and Linux ABI.
    with tempfile.TemporaryDirectory(prefix=".resolve-install-", dir=project) as work:
        work = Path(work)
        environment = work / "venv"
        venv.EnvBuilder(with_pip=True).create(environment)
        staged = work / "deps"
        subprocess.run([str(environment / "bin/python"), "-m", "pip", "install",
                        "--requirement", str(project / "requirements-resolve.txt"),
                        "--target", str(staged)], check=True)
        env = dict(os.environ, PYTHONPATH=os.pathsep.join((str(staged), str(project / "src"))),
                   PYTHONNOUSERSITE="1")
        subprocess.run([sys.executable, "-c",
                        "import yaml; from PIL import Image; import resolve_timer.ui; "
                        "Image.new('RGB', (1, 1)).save(__import__('io').BytesIO(), format='PNG'); "
                        "print('Dependency and UI imports passed')"], env=env, check=True)
        subprocess.run([sys.executable, "-m", "resolve_timer.cli", "--db",
                        str(project / "timer_db.yaml" if (project / "timer_db.yaml").exists()
                            else project / "examples/timer_db.yaml"), "validate-db"],
                       env=env, check=True)
        backup = work / "previous-deps"
        if target.exists():
            target.rename(backup)
        try:
            staged.rename(target)
            install_launcher(project, launcher)
        except Exception:
            if target.exists():
                shutil.rmtree(target)
            if backup.exists():
                backup.rename(target)
            raise
    print("Installed. Restart Resolve, then open Workspace > Scripts > Resolve Timer.")


if __name__ == "__main__":
    try:
        main()
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"Installation failed: {exc}", file=sys.stderr)
        sys.exit(1)
